# Site settings
title:
email: snehita@thecollegecommunity.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ninazanarelli.github.io" # the base hostname & protocol for your site

github_username: ninazanarelli
phone_number: 5187728733

# Build settings
markdown: kramdown
